create table O_sales
(
    sales_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
    refNumDate NUMBER(20),
    refReview VARCHAR2(50),
    refLocation VARCHAR2(50),
    refSeller VARCHAR2(50),
    refProduct VARCHAR2(50),
    chiffre_affaire NUMBER(38,3) ,
    constraint pk_O_sales PRIMARY KEY(sales_id)
)
PARTITION BY RANGE(chiffre_affaire)
(PARTITION part1 VALUES LESS THAN (50) 
 );
 
INSERT INTO O_sales(refNumDate,refReview,refLocation,refSeller,refProduct,chiffre_affaire) 
select refNumDate,refReview,refLocation,refSeller,refProduct,chiffre_affaire from D_sales ; 

create table O_sellers
(
    seller_id  VARCHAR2(50),
    zip_code varchar2(50),
    city VARCHAR2(50) ,
    constraint pk_sel primary key(zip_code)
)PARTITION BY RANGE(zip_code)
(PARTITION part1 VALUES LESS THAN (42300) 
 );



create table O_date
(
    numDate NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
    order_id VARCHAR(50) ,
    mois NUMBER(10),
    annee NUMBER(10),
    dayOfWeek NUMBER(10)
 constraint pk_da primary key(numDate)
)PARTITION BY RANGE(annee)
(PARTITION part1 VALUES LESS THAN (2017) ,
 PARTITION part2 VALUES LESS THAN (2018)
 );


create table O_products
(
    product_id  VARCHAR2(50),
    product_category_name VARCHAR2(50),
    product_photos_qty NUMBER(10)
 constraint pk_pproduct_id primary key(product_id)
)PARTITION BY RANGE(product_photos_qty)
(PARTITION part1 VALUES LESS THAN (4) ,
 PARTITION part2 VALUES LESS THAN (6)
 );



create table D_reviews
(
    review_id  VARCHAR2(50),
    review_score NUMBER(10),
    review_comment_title VARCHAR2(50)    
constraint pkreview_idt_id primary key(review_id)
)PARTITION BY RANGE(review_score)
(PARTITION part1 VALUES LESS THAN (4) ,
 PARTITION part2 VALUES LESS THAN (6)
 );



create table D_location
(
    zip_code  VARCHAR2(50),
    city VARCHAR2(50)    
 constraint pk_cation primary key(zip_code)
)PARTITION BY RANGE(zip_code)
(PARTITION part1 VALUES LESS THAN (42300) 
 );

 
