create table D_sales
(
    sales_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
    refNumDate NUMBER(20),
    refReview VARCHAR2(50),
    refLocation VARCHAR2(50),
    refSeller VARCHAR2(50),
    refProduct VARCHAR2(50),
    chiffre_affaire NUMBER(38,3)
);


create table D_sellers
(
    seller_id  VARCHAR2(50),
    zip_code varchar2(50),
    city VARCHAR2(50)
);



create table D_date
(
    numDate NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
    order_id VARCHAR(50) ,
    mois NUMBER(10),
    annee NUMBER(10),
    dayOfWeek NUMBER(10)
);


create table D_products
(
    product_id  VARCHAR2(50),
    product_category_name VARCHAR2(50),
    product_photos_qty NUMBER(10)
);



create table D_reviews
(
    review_id  VARCHAR2(50),
    review_score NUMBER(10),
    review_comment_title VARCHAR2(50)    
);


create table D_location
(
    zip_code  VARCHAR2(50),
    city VARCHAR2(50)    
);

 
alter table D_location 
add constraint pk_loc primary key (zip_code);

alter table D_reviews 
add constraint pk_review primary key (review_id);

alter table D_products 
add constraint pk_product primary key (product_id);

alter table D_date
add constraint pk_date primary key (numDate);

alter table D_sellers
add constraint pk_seller primary key (seller_id);

alter table D_sales
add constraint pk_sales primary key(sales_id);

alter table D_sales
add constraint fk_seller foreign key(refseller) REFERENCES D_sellers(seller_id);


alter table D_sales
add constraint fk_product foreign key(refProduct) REFERENCES D_products(product_id);

alter table D_sales
add constraint fk_date foreign key(refNumDate) REFERENCES D_date(numDate);

alter table D_sales
add constraint fk_locat foreign key(refLocation) REFERENCES D_location(zip_code);

alter table D_sales
add constraint fk_review foreign key(refReview) REFERENCES D_reviews(review_id);
-------desactivation des contraintes----------------------------

alter table D_sales disable constraint fk_locat;
alter table D_sales disable constraint fk_date;
alter table D_sales disable constraint fk_product;
alter table D_sales disable constraint fk_seller;
alter table D_sales disable constraint fk_review;
alter table D_sales disable constraint pk_sales;
alter table D_date disable constraint pk_date;
alter table D_sellers disable constraint pk_seller;
alter table D_location disable constraint pk_loc;
alter table D_products disable constraint pk_product;
alter table D_reviews disable constraint pk_review;

----------------Copie des donnees de la zone transformation vers DW----------------------------------

INSERT INTO D_date(order_id,mois, annee, dayOfWeek)
SELECT  i.getOrder_id(),i.getMonth(), i.getYear(), i.getDayOfWeek()
FROM T_items i;

INSERT INTO D_sellers
SELECT  s.getSeller_id (),s.getSeller_zip_code_prefix() ,s.getSeller_city()
FROM T_sellers s;

INSERT INTO D_reviews
SELECT  r.getReview_id(), r.getReview_score(),r.getReview_comment_title()
FROM T_reviews r;

INSERT INTO D_location
SELECT  g.getGzip(),g.getGcity()
FROM T_geolocation g;

INSERT INTO D_products
SELECT  p.getProduct_id(), p.getProduct_category_name(), p.getProduct_photos_qty()
FROM T_products p;

insert into D_sales(refNumDate,refReview, refLocation, refSeller, refProduct, chiffre_affaire)
select d.numDate,r.getReview_id(),l.getGzip(),s.getSeller_id(), p.getProduct_id(),(i.getPrice()+i.getFreight_value())*i.getOrder_item_id()*0.21
from T_items i , T_reviews r , T_geolocation l , T_products p, T_sellers s,D_date d
where i.seller_id = s.seller_id
and i.product_id = p.product_id
and s.seller_zip_code_prefix = l.geolocation_zip_code_prefix
and  i.order_id =r.order_id 
and i.order_id=d.order_id;

select * from D_sales ;

------------------------------------------------------------------------------------ 
-------desactivation des contraintes----------------------------

alter table D_sales ENABLE constraint fk_locat EXCEPTIONS INTO exceptions;
alter table D_sales ENABLE constraint fk_date EXCEPTIONS INTO exceptions;
alter table D_sales ENABLE constraint fk_product EXCEPTIONS INTO exceptions;
alter table D_sales ENABLE constraint fk_seller EXCEPTIONS INTO exceptions;
alter table D_sales ENABLE constraint fk_review EXCEPTIONS INTO exceptions;
alter table D_sales ENABLE constraint pk_sales EXCEPTIONS INTO exceptions;
alter table D_date ENABLE constraint pk_date EXCEPTIONS INTO exceptions;
alter table D_sellers ENABLE constraint pk_seller EXCEPTIONS INTO exceptions;
alter table D_location ENABLE constraint pk_loc EXCEPTIONS INTO exceptions;
alter table D_products ENABLE constraint pk_product EXCEPTIONS INTO exceptions;
alter table D_reviews ENABLE constraint pk_review EXCEPTIONS INTO exceptions;
---------------------------------------------------------------------------------------
----- indx 
select reflocation,count(chiffre_affaire) from D_sales 
group by reflocation ;
select * from D_products ;
select * from D_sales ; 
select * from D_location ;
select  * FROM d_date ; 
select * from d_products; 

select l.city , p.product_category_name ,sum(s.chiffre_affaire) "CA"
from D_sales s,d_products p , d_location l 
where s.refproduct=p.product_id and s.reflocation=l.zip_code
group by l.city ,p.product_category_name 
Order by CA; 

select d.mois,'Chiffre affaire/mois',count(s.chiffre_affaire)
,d.annee,'Chiffre affaire/annee'
from D_sales s ,  D_date d  where  s.refNumDate = d.numDate
GROUP BY d.mois,d.annee
order by d.annee



select l.city,count(s.chiffre_affaire) from D_sales s,D_location l 
where s.reflocation=l.zip_code
group by l.city ;


